### ISSUE TITLE
[Question] Whats the difference between this 2 libs?

### ISSUE THREAD

**Issue by tetreum** [marvinroger/node-lumi-aqara#14]
What's the difference between your lib and this one?
https://github.com/aholstenson/miio

**Comment by marvinroger** [comment]
miio operates on the MiHome Binary Protocol. It supports all Xiaomi devices that implement this protocol.

This library, on the other hand, uses the specialized API exposed by the Xiaomi Gateway. Looking [at this](https://github.com/aholstenson/miio/blob/master/docs/devices/README.md), it seems that the MiHome Binary Protocol is not as featured as the API that we use, for example, you cannot control the light.

**Comment by tetreum** [comment]
Oh, interesting! i thought that the API only exposed some parts of MiHome Binary Protocol.
If Xiaomi Cloud/MiCloud service closes/goes down,  this lib will remain active without any problem? 
I mean, is it an alternative for full "offcloud" use?

**Comment by marvinroger** [comment]
Yes, it is, with the exception that you cannot upload your custom sounds to the gateway using the API. Other than that, it's fully functional. 😉
