### ISSUE TITLE
write_ack

### ISSUE THREAD

**Issue by adamcoquelet** [marvinroger/node-lumi-aqara#33]
Error when interacting with the gateway (color and sound)

gateway.setColor({ r: 255, g: 0, b: 0 })
 gateway.setIntensity(100)
 gateway.setSound(11,50)

Return :

not handled: {"cmd":"write_ack","sid":"34ce0089260c","data":"{\"error\":\"Invalid key\"}"}

**Comment by marvinroger** [comment]
Did you set the correct password?
