### ISSUE TITLE
Control alarm status?

### ISSUE THREAD

**Issue by svrooij** [marvinroger/node-lumi-aqara#4]
Would it also be possible to control the alarm status?
The gateway has some nice alarm feature, that makes a hell off a sound if it is `armed` and a door/window is opened.

But the application to turn it on and off kinda sucks, so I would like to control the armed status some other way.

**Comment by marvinroger** [comment]
As far as I know, the API does not (yet?) allow to do this. So until Xiaomi updates it's firmware, it won't be possible.

**Comment by svrooij** [comment]
Do you know if there is some sort of documentation about this gateway? Because if the app can do it, it should also be possible with a direct gateway command.

**Comment by svrooij** [comment]
[api documentation](https://louiszl.gitbooks.io/lumi-gateway-local-api/content/) if you're interested (and using google translate).

Only thing possible is to play sounds (not tried yet). Alarm seems to be in the Mihome cloud.

As off now my [xiaomi2mqtt](https://github.com/svrooij/node-xiaomi2mqtt) is available and depends on this library.
